---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.34.1
    app.quarkus.io/commit-id: 68c18d9600b0f85b6c6cfbf58b02caa70c8eb8fa
    app.quarkus.io/vcs-uri: https://github.com/mcruzdev/agentic-ai-durable.git
    app.quarkus.io/build-timestamp: 2026-03-31 - 04:32:18 +0000
  labels:
    app.kubernetes.io/part-of: quarkus-flow
    app.kubernetes.io/name: durable-flow-demo
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app: durable-flow-demo
    app.kubernetes.io/managed-by: quarkus
  name: durable-flow-demo
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.34.1
    app.quarkus.io/commit-id: 68c18d9600b0f85b6c6cfbf58b02caa70c8eb8fa
    app.quarkus.io/vcs-uri: https://github.com/mcruzdev/agentic-ai-durable.git
    app.quarkus.io/build-timestamp: 2026-03-31 - 04:32:18 +0000
  labels:
    app.kubernetes.io/part-of: quarkus-flow
    app.kubernetes.io/name: durable-flow-demo
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app: durable-flow-demo
    app.kubernetes.io/managed-by: quarkus
  name: durable-flow-demo
  namespace: default
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - apps
    resources:
      - deployments
      - replicasets
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.34.1
    app.quarkus.io/commit-id: 68c18d9600b0f85b6c6cfbf58b02caa70c8eb8fa
    app.quarkus.io/vcs-uri: https://github.com/mcruzdev/agentic-ai-durable.git
    app.quarkus.io/build-timestamp: 2026-03-31 - 04:32:18 +0000
  labels:
    app.kubernetes.io/part-of: quarkus-flow
    app.kubernetes.io/name: durable-flow-demo
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app: durable-flow-demo
    app.kubernetes.io/managed-by: quarkus
  name: durable-flow-demo
  namespace: default
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: durable-flow-demo
subjects:
  - kind: ServiceAccount
    name: durable-flow-demo
    namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.34.1
    app.quarkus.io/commit-id: 68c18d9600b0f85b6c6cfbf58b02caa70c8eb8fa
    app.quarkus.io/vcs-uri: https://github.com/mcruzdev/agentic-ai-durable.git
    app.quarkus.io/build-timestamp: 2026-03-31 - 04:32:18 +0000
  labels:
    app.kubernetes.io/part-of: quarkus-flow
    app.kubernetes.io/name: durable-flow-demo
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app: durable-flow-demo
    app.kubernetes.io/managed-by: quarkus
  name: durable-flow-demo-legacy-newsletter-drafter
  namespace: default
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: durable-flow-demo
subjects:
  - kind: ServiceAccount
    name: newsletter-drafter
    namespace: default
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.34.1
    app.quarkus.io/commit-id: 68c18d9600b0f85b6c6cfbf58b02caa70c8eb8fa
    app.quarkus.io/vcs-uri: https://github.com/mcruzdev/agentic-ai-durable.git
    app.quarkus.io/build-timestamp: 2026-03-31 - 04:32:18 +0000
    prometheus.io/scrape: "true"
    prometheus.io/path: /q/metrics
    prometheus.io/port: "8080"
    prometheus.io/scheme: http
  labels:
    app.kubernetes.io/name: durable-flow-demo
    app.kubernetes.io/part-of: quarkus-flow
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app: durable-flow-demo
    app.kubernetes.io/managed-by: quarkus
  name: durable-flow-demo
  namespace: default
spec:
  ports:
    - name: http
      nodePort: 31919
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: durable-flow-demo
    app.kubernetes.io/part-of: quarkus-flow
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.34.1
    app.quarkus.io/commit-id: 68c18d9600b0f85b6c6cfbf58b02caa70c8eb8fa
    app.quarkus.io/vcs-uri: https://github.com/mcruzdev/agentic-ai-durable.git
    app.quarkus.io/build-timestamp: 2026-03-31 - 04:32:18 +0000
    prometheus.io/scrape: "true"
    prometheus.io/path: /q/metrics
    prometheus.io/port: "8080"
    prometheus.io/scheme: http
  labels:
    app.kubernetes.io/name: durable-flow-demo
    app.kubernetes.io/part-of: quarkus-flow
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app: durable-flow-demo
    app.kubernetes.io/managed-by: quarkus
  name: durable-flow-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/part-of: quarkus-flow
      app.kubernetes.io/name: durable-flow-demo
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
  template:
    metadata:
      annotations:
        app.quarkus.io/quarkus-version: 3.34.1
        app.quarkus.io/commit-id: 68c18d9600b0f85b6c6cfbf58b02caa70c8eb8fa
        app.quarkus.io/vcs-uri: https://github.com/mcruzdev/agentic-ai-durable.git
        app.quarkus.io/build-timestamp: 2026-03-31 - 04:32:18 +0000
        prometheus.io/scrape: "true"
        prometheus.io/path: /q/metrics
        prometheus.io/port: "8080"
        prometheus.io/scheme: http
      labels:
        app: durable-flow-demo
        app.kubernetes.io/managed-by: quarkus
        app.kubernetes.io/part-of: quarkus-flow
        app.kubernetes.io/name: durable-flow-demo
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
    spec:
      containers:
        - env:
            - name: QUARKUS_REDIS_HOSTS
              value: redis://redis.default.svc.cluster.local:6379
            - name: MP_MESSAGING_CONNECTOR_SMALLRYE_KAFKA_BOOTSTRAP_SERVERS
              value: "PLAIN_TEXT://kafka.default.svc.cluster.local:9092"
            - name: OPENAI_API_KEY
              value: ""
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          image: docker.io/matheuscruzdev/newsletter-drafter:1.0.0-SNAPSHOT
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          name: durable-flow-demo
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          startupProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/started
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
      serviceAccountName: durable-flow-demo
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.34.1
    app.quarkus.io/commit-id: 68c18d9600b0f85b6c6cfbf58b02caa70c8eb8fa
    app.quarkus.io/vcs-uri: https://github.com/mcruzdev/agentic-ai-durable.git
    app.quarkus.io/build-timestamp: 2026-03-31 - 04:32:18 +0000
  labels:
    app.kubernetes.io/name: durable-flow-demo
    app.kubernetes.io/part-of: quarkus-flow
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app: durable-flow-demo
    app.kubernetes.io/managed-by: quarkus
  name: durable-flow-demo
  namespace: default
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: durable-flow-demo
      app.kubernetes.io/part-of: quarkus-flow
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
  endpoints:
    - scheme: http
      targetPort: 8080
      path: /q/metrics
      interval: 10s
      honorLabels: true
