apiVersion: v1
kind: ConfigMap
metadata:
  name: infra-config
data:
  QUARKUS_REDIS_HOSTS: "redis://redis.default.svc.cluster.local:6379"
  MP_MESSAGING_CONNECTOR_SMALLRYE_KAFKA_BOOTSTRAP_SERVERS: "PLAIN_TEXT://kafka.default.svc.cluster.local:9092"