# Kubernetes
quarkus.kubernetes.namespace=default
quarkus.kubernetes.name=newsletter-drafter
quarkus.kubernetes.part-of=quarkus-flow
quarkus.kubernetes.version=1.0.0-SNAPSHOT
quarkus.kubernetes.labels.app=newsletter-drafter
quarkus.kubernetes.ports.http.container-port=8080

quarkus.container-image.build=true
quarkus.container-image.image=matheuscruzdev/newsletter-drafter:latest
# Jib
quarkus.jib.base-jvm-image=registry.access.redhat.com/ubi9/openjdk-21:1.23
quarkus.jib.use-current-timestamp=true
quarkus.container-image.push=false

quarkus.kubernetes.deploy=true

quarkus.kubernetes.deployment-target=kind
quarkus.kubernetes.image-pull-policy=IfNotPresent
quarkus.kubernetes.replicas=2
quarkus.kubernetes.deployment-kind=deployment
quarkus.kubernetes.strategy=recreate
quarkus.kubernetes.service-account=newsletter-drafter

quarkus.kubernetes-client.generate-rbac=true
quarkus.kubernetes.rbac.service-accounts.newsletter-drafter.use-as-default=true

quarkus.kubernetes.rbac.roles.newsletter-drafter.policy-rules.0.api-groups=
quarkus.kubernetes.rbac.roles.newsletter-drafter.policy-rules.0.resources=pods
quarkus.kubernetes.rbac.roles.newsletter-drafter.policy-rules.0.verbs=get

quarkus.kubernetes.rbac.roles.newsletter-drafter.policy-rules.1.api-groups=coordination.k8s.io
quarkus.kubernetes.rbac.roles.newsletter-drafter.policy-rules.1.resources=leases
quarkus.kubernetes.rbac.roles.newsletter-drafter.policy-rules.1.verbs=get,list,watch,create,update,patch,delete

quarkus.kubernetes.rbac.roles.newsletter-drafter.policy-rules.2.api-groups=apps
quarkus.kubernetes.rbac.roles.newsletter-drafter.policy-rules.2.resources=deployments,replicasets
quarkus.kubernetes.rbac.roles.newsletter-drafter.policy-rules.2.verbs=get,list,watch

quarkus.kubernetes.rbac.role-bindings.newsletter-drafter.subjects.newsletter-drafter.kind=ServiceAccount
quarkus.kubernetes.rbac.role-bindings.newsletter-drafter.subjects.newsletter-drafter.namespace=default
quarkus.kubernetes.rbac.role-bindings.newsletter-drafter.role-name=newsletter-drafter

quarkus.kubernetes.env.fields.POD_NAME=metadata.name
quarkus.kubernetes.env.fields.POD_NAMESPACE=metadata.namespace

# we don't need ServiceMonitor since Prometheus operator is not installed
quarkus.kubernetes.prometheus.generate-service-monitor=false

# create before deploying: k create secret generic openai-credentials --from-literal=api-key=<THE KEY>
quarkus.kubernetes.env.mapping.OPENAI_API_KEY.from-secret=openai-credentials
quarkus.kubernetes.env.mapping.OPENAI_API_KEY.with-key=api-key

# configMap for our infra connection
quarkus.kubernetes.env.configmaps=infra-config

quarkus.kubernetes.env.vars.quarkus-flow=infra-connection-string
